# Generated by Django 6.0.2 on 2026-03-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField()),
                ('userid', models.SlugField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
