# Generated by Django 6.0.2 on 2026-03-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.SlugField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='', max_length=75)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('team_members', models.ManyToManyField(related_name='teams', to='users.user')),
            ],
        ),
    ]
