# Generated by Django 6.0.2 on 2026-02-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.SlugField()),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('team_members', models.ManyToManyField(related_name='teams', to='users.user')),
            ],
        ),
    ]
