# Generated by Django 6.0.2 on 2026-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.SlugField(unique=True),
        ),
    ]
